apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-crud-api
  namespace: serverless-demo
spec:
  template:
    spec:
      containers:
        - image: quay.io/swinches/tutorial-crud-api:latest
          env:
          - name: DATABASE_SERVICE_NAME
            value: tutorial1-tutorial-crud-api-mongo
          - name: TUTORIAL1_TUTORIAL_CRUD_API_MONGO_SERVICE_HOST
            value: 172.30.242.244
          - name: MONGODB_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: tutorial1-tutorial-crud-api
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: tutorial1-tutorial-crud-api
          - name: MONGODB_DATABASE
            value: sampledb
          - name: MONGODB_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-admin-password
                name: tutorial1-tutorial-crud-api
